store/urls.py
  
from django.contrib import admin
from django.urls import path
from . import views

app_name= 'store'

urlpatterns = [
    path('', views.index, name='home'),
    path('<str:biz_url>', views.index, name='index'),
    path('new/<str:biz_url>', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),
    path('<int:order_id>/delete/', views.delete, name='delete'),
    path('order_history/', views.order_history, name='order_history'),  
    path('review/<int:order_id>', views.review, name='review'),
    path('review_create/<int:order_id>', views.review_create, name='review_create'),
    #path('review/', views.review, name='review'),
    path('myprofile/', views.myprofile, name='myprofile'),
]

sweet_new/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('manager/', include('manager.urls')),
    path('accounts/', include('accounts.urls')),
    path('store/', include('store.urls', namespace="review")),
]

manager/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Store(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    biz_name = models.CharField(max_length=10, null=True)
    biz_num = models.IntegerField(null=True)
    biz_url = models.CharField(max_length=15, unique=True, null=True)
    biz_insta = models.CharField(max_length=15, null=True)
    biz_address = models.CharField(max_length=40, null=True)
    biz_tel = models.CharField(max_length=15, null=True)

    def __str__(self):
        return f'가게명:{self.biz_name} 인스타아이디:{self.biz_insta} URL:/{self.biz_url}'


class Allitem(models.Model):
    store = models.ForeignKey('Store', on_delete=models.CASCADE, null=True)
    item_category = models.CharField(max_length=10)
    item_name = models.CharField(max_length=10)
    item_price = models.IntegerField(null=True)

    def __str__(self):
        return f'가게명:{self.store.biz_name} 카테고리:{self.item_category} 품목명:{self.item_name} 가격:{self.item_price}'

class Today_lineup(models.Model):
    store = models.ForeignKey('Store', on_delete=models.CASCADE, null=True)
    item = models.ForeignKey('Allitem', on_delete=models.PROTECT, null=True)
    set_day = models.DateField()
    quota = models.IntegerField()
    

    def __str__(self):
        return f'품목:{self.item.item_name} / 판매날짜:{self.set_day} / 재고:{self.quota}'


class Store_set(models.Model):
    store = models.ForeignKey('Store', on_delete=models.CASCADE, null=True)
    openday = models.DateField()
    opentime = models.TimeField()
    pickuptime = models.TimeField(null=True)
    notification = models.CharField(max_length=50, null=True)

    def __str__(self):
        return f'가게명:{self.store.biz_name} 오픈날짜:{self.openday}'


#리뷰모델은 customer app에서 만들 것

store/models.py
from django.db import models
from django.contrib.auth.models import User
from manager.models import Store, Today_lineup, User, Store_set, Allitem

# Create your models here.

class Customer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    cus_insta = models.CharField(max_length=15, unique=True)
    

    def __str__(self):
        return f'userPK고객이름:{self.user.first_name} 인스타아이디:{self.cus_insta}'

class Order(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    ##주문한시간 셋데이만 들어가면!! 이것만 들어가면 가동이안됨..
    #set_day = models.DateField() 
    order_date = models.DateTimeField(auto_now_add=True)
    pickuptime = models.TimeField(null=True)
    picktf = models.BooleanField(null=True)
    reservetf = models.BooleanField(null=True)
    def __str__(self):
        return f'store:{self.store.biz_name} first_name:{self.user.first_name} pickuptime:{self.pickuptime} picktf:{self.picktf} reservetf:{self.reservetf}'
    

class Orderlist(models.Model):
    order_number = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)
    today_lineup = models.ForeignKey(Today_lineup, on_delete=models.CASCADE, null=True)
    order_quota = models.IntegerField()

def __str__(self):
        return f'order_number:{self.order} / Today_lineup:{self.today_lineup.id} / order_quota:{self.order_quota}'
#foreignkey 안에서는 id 적지 않아도 알아서 생긴다! 
class Review(models.Model):
    order = models.ForeignKey(Order,on_delete=models.SET_NULL, null=True)
   
    #models.ForeignKey(Order, on_delete=models.CASCADE)
    review_content = models.CharField(max_length=300)
    review_photo = models.ImageField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return f'order:{self.order} / review_content:{self.review_content}/ review_photo:{self.review_photo}'

store/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.utils import timezone
from manager.models import Store, Today_lineup, User, Store_set, Allitem
from store.models import Order, Orderlist, Customer, Review
# Create your views here.
def new(request):
    # teststore = Store.objects.get(today_lineup.id)
    # test = Today_lineup.objects.filter(store=teststore)
    # testitem = Today_lineup.objects.filter(store=teststore)
    # testquota = Today_lineup.objets.filter(store=teststore)
    # testprice = Allitem.objects.get(allitem.id == today_lineup.item)
    
    # context={
    #     "teststore":teststore,
    #     "test":test,
    #     "testitem":testitem,
    #     "testquota":testquota,
    #     "testprice":testprice,
    #     }
    return render(request,'store/new.html')
    #여기 리턴에서 , context 뺌 
#balance에서 갖고 오기 나중에는 
def create(request):
    #set_day = request.POST['set_day'] 셋데이 여기서 빼고, 밑에 order=Order(set_day 여기서도 뺐다)
    pickuptime = request.POST['pickuptime']
    today_lineup = request.POST['today_lineup']
    order_quota = request.POST['order_quota']
    ordered_date = request.POST['orderd_date']
    order = Order(pickuptime=pickuptime, orderedate=timezone.now())
    orderlist = Orderlist(today_lineup=today_lineup, order_quota=order_quota)
    order.save()
    orderlist.save()
#누구누구님안녕하세요 기능넣고, first_name order db로 넘기기 
    return redirect('store:order_detail', order_id=order.id)    

def index(request):

    return render(request, 'store/index.html')

def delete(request):
    return redirect('store:index')
#order.id 뺌, detail history에서, 그리고 히스토리에서, context 도 뺌
@login_required
def order_detail(request, order_id):
    #이게 create 함수 바로 이어지는 페이지다. 
    try:
        result = Order.objects.get(id=order_id, user=request.user)
    except Order.DoesNotExist:
        return redirect('store:index')

    order = Order.objects.get(id=order_id)
   
    dtstore = Order.objects.get(id=order_id)
    dtlineup = Orderlist.objects.get(id=order_id)
    dtquota = Orderlist.objects.get(id=order_id)
    dtprice = Orderlist.objects.get(id=order_id)
    #totalprice = sum{dtquota * dtprice } 이렇게 html 에 적기! 
    dtpickuptime = Order.objects.get(id=order_id)
    dtorderdate = Order.objects.get(id=order_id)
    
    context = { 'order':order,
                'dtstore':dtstore,
                'dtlineup':dtlineup,
                'dtquota':dtquota,
                'dtprice':dtprice,
                'dtpickuptime':dtpickuptime,
                'dtorderdate':dtorderdate,
                }
    return render(request, 'store/order_detail.html', context)
@login_required
def order_history(request, order_id):
    try:
        result = Order.objects.get(id=order_id, user=request.user)
    except Order.DoesNotExist:
        return redirect('store:index')
    
       order = Order.objects.get(id=order_id)
   
    dtstore = Order.objects.get(id=order_id)
    dtlineup = Orderlist.objects.get(id=order_id)
    dtquota = Orderlist.objects.get(id=order_id)
    dtprice = Orderlist.objects.get(id=order_id)
    #totalprice = sum{dtquota * dtprice } 이렇게 html 에 적기! 
    dtpickuptime = Order.objects.get(id=order_id)
    dtorderdate = Order.objects.get(id=order_id)
    
    context = { 'order':order,
                'dtstore':dtstore,
                'dtlineup':dtlineup,
                'dtquota':dtquota,
                'dtprice':dtprice,
                'dtpickuptime':dtpickuptime,
                'dtorderdate':dtorderdate,
                }
    return render(request, 'store/order_history.html', context)
@login_required
def review_history(request, review_id):
    try:
        result = Reivew.objects.get(id=review_id, user=request.user)
    except Order.DoesNotExist:
        return redirect('store:index')

    review = Review.objects.get(id=order_id)
    
    dtcomment = Review.objects.get(id=review_id)
    dtrpicture = Review.objects.get(id=review_id)
    dtrcreated = Review.objects.get(id=review_id)

     context = { 'review':review,
                'dtcomment':dtcomment,
                'dtrpicture':dtrpicture,
                'dtrcreated':dtrcreated,
                }
 return render(request, 'store/review_history.html', context)
    #먼저 고객 id를 확인해 - 본인이 맞는지 체크도 하고 
    #그고객의 주번들을 불러와 그리고 그 주번의 가게이름/메뉴/예약날짜/픽업시간/결제금액을 불러와 
    # order=Order.objects.filter(User.id=user.get_username)
    # order=Order.objects.get(id=order_id)
    # context = {'post':post} 와 진짜어렵다. 유저네임으로 오더불러오고 내용도 채워야하는거잔항

#리뷰=리뷰 눌렀을 때 액션 // review create = 리뷰 submit 했을 때 액션
def review(request, order_id):
    return render(request, 'store/review.html')

def review_create(request, order_id):
    #order = get_object_or_404(Order, pk=order_id)
    
    order = Order.objects.get(id=order_id)
    review_content = request.POST['review_content']
    #review_content = Review.objects.create(review_content=review_content)
    # if order_id == None:
    #     return Httpresponse("주문번호를 입력해주세요")
    # elif review_content == None:
    #     return Httpresponse("리뷰 내용을 입력해주세요")
    review_content.save()
    return redirect('store:order_detail', order_id=order.id)
#     review = request.POST['review']
#     review = Review(order = order, review = review)
#     review.save()
#     return redirect('')
# Create your views here.

def myprofile(request):
    return render(request, 'store/myprofile.html')

store/templates/store/home.html
{% load static %}

{% block style %}
  
    <link rel="stylesheet" type="text/css" href="{% static 'store/style.css'%}" />
  
{% endblock %}

{% block content %}

  <h1>스윗폼 소개페이지</h1>
  <img src="static/macaron.png" alt="{{Store.biz_name}}" width="900" height="600">
  <p>{{ user.first_name}} 님 환영합니다. </p>

store/templates/store/index.html
{% load static %}

{% block style %}
  
    <link rel="stylesheet" type="text/css" href="{% static 'store/style.css'%}" />
  
{% endblock %}

{% block content %}

  <h1>가게 소개 페이지</h1>
  <img src="static/macaron.png" alt="{{Store.biz_name}}" width="900" height="600">
  <p>{{ user.first_name}} 님 환영합니다. </p>
  <p>{{Store.biz_name}}</p>
  <h2> 예약하실 날짜를 입력해주세요</h2>
  <input type="date" name="date" >
  <h2>가게소개글</h2>
  <div style="border:1px padding 0px">안녕하세요</div>
  <h2>리뷰</h2>
  <div style="border:1px padding 0px">안녕하세요</div>
  <h2>가게정보</h2>
  
  {% if posts %}
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>가게이름</th>
          <th>인스타아이디</th>
          <th>전화번호</th>
          <th>가게주소</th>
        </tr>
      </thead>
      <tbody>
        {% for post in posts %}
        <tr>
          <th>{{ Store.biz_name}}</th>
          <td>{{ post.biz_insta }}</td>
          <td>{{ post.biz_tel }}</td>
          <td>{{ post.biz_address }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
      <p>No Posts.</p>
    {% endif %}

  <style>
    .button1 {display:inline-block; background-color:#f44336; color: #FFFFFF; padding: 14px 25px; text-align: center; text-decoration: none; font-size: 16px; margin-left: 20px; opacity: 0.9; border-radius: 5px;} 
    .button1:hover {color:white; background-color:pink; opacity:1.0;}
  </style>  
  <a href="{% url 'store:new' %}" class="button1" targer="_blank">예약하기</a>
</div>
 

{% endblock %}

store/templates/store/main.html
{% extends "base.html" %}

{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'store/style.css'%}" />
{% endblock %}

{% block content %}
  <div class="container">
    <h1 class="page_title">스윗폼 첫페이지 </h1>
    <!--<a href="{% url 'manager:new' %}">업체등록하러가기</a>  이거를 마이페이지에다가만? -->
</div>
 {% endblock %}

store/templates/store/myprofile.html
{% load static %}

{% block style %}
  
    <link rel="stylesheet" type="text/css" href="{% static 'store/style.css'%}" />
  
{% endblock %}
<ul>
    <li>내ID </li>
    <li>내 이름</li>
    <li>구매내역</li>
    <li>리뷰내역</li>

</ul>

store/templates/store/new.html
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'store/style.css'%}" />
{% endblock %}

{% block content %}
  <h1>예약페이지</h1>

    <form action="{% url 'store:create' %}" method="POST">
    {% csrf_token %}

    <h2>날짜</h2>
    <input type="text" name="set_day" />

    <h2>픽업시간</h2>
    <input type="text" name="pickuptime" />
   
    <h3>사장님 메세지</h3>
    <textarea cols="40" rows="10" name="notification"></textarea>


    <h2>메뉴</h2>
    {% if test %}
    <table>
      <thead>
        <tr>
          <th>메뉴</th>
          <th>재고</th>
          <th>가격</th>
          <th>주문수량</th>
        </tr>
      </thead>
      <tbody>
        {% for x in test %}
        <tr>  
            <td>{{ x.item }}</td>
            <td>{{ x.quota }}</td>
            <td>{{ x.item_price }}</td>
            <td><input type="number" name="order_quota" id="order_quota"></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
      <p>No Posts.</p>
    {% endif %}
    <h2>포장방법</h2>
    <input type="text" name="author" />
    <h2>예약자정보</h2>
    {% if test %}
    <table>
        <thead>
            <tr>
                <th>예약자 이름</th>
                <th>예약자 연락처</th>
            </tr>
        </thead>
        <tbody>
            {% for x in customer %}
            <tr>
                <th>{{ customer.first_name }}</th>
                <th>{{ user.username }}</th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>No Posts.</p>
    {% endif %}
    <br />
    <input type="submit" class=button1 value="예약하기">

  </form>
  <style>
    .button1 {display:inline-block; background-color:#f44336; color: #FFFFFF; padding: 14px 25px; text-align: center; text-decoration: none; font-size: 16px; margin-left: 20px; opacity: 0.9; border-radius: 5px;} 
    .button1:hover {color:white; background-color:pink; opacity:1.0;}
  </style>  
  <a href="{% url 'store:index' %}" class="button1" targer="_blank">이전으로</a>


{% endblock %}

store/templates/store/order_detail.html
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'store/style.css'%}" />
{% endblock %}

{% block content %}
  <h1>구매내역</h1>
  {{test_variable}}
  {% if post %}
    <table>
      <thead>
        <tr>
          <tr>주문번호</tr>
          <tr>가게이름</tr>
          <tr>메뉴</tr>
          <tr>수량</tr>
          <tr>예약날짜</tr>
          <tr>픽업시간</tr>
        </tr>
      </thead>
      <tbody>
        {% for post in posts%}
        <tr>
          <th>{{ order.id }}</th>
          <th>{{ order.store }}</th>
          <th>{{ orderlist.today_lineup }}</th>
          <th>{{ orderlist.order_quota }}</th>
          <th>{{ order.ordered_date }}</th>
          <th>{{ order.pickuptime }}</th>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>No Post.</p>
  {% endif %}
  <h2>사장님메세지칸</h2>
  <p>{{ store_set.notification}}</p>
  <h2>가게정보</h2>

  <style>
    .button1 {display:inline-block; background-color:#f44336; color: #FFFFFF; padding: 14px 25px; text-align: center; text-decoration: none; font-size: 16px; margin-left: 20px; opacity: 0.9; border-radius: 5px;} 
    .button1:hover {color:white; background-color:pink; opacity:1.0;}
  </style>  
  <a href="{% url 'store:index' %}" class="button1" targer="_blank">메인페이지</a>
  
{% endblock %}

store/templates/store/order_history.html
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'store/style.css'%}" />
{% endblock %}

{% block content %}
  <h1>나의구매내역</h1>


  {% if post %}
    <table>
      <thead>
        <tr>
          <tr>주문번호</tr>
          <tr>가게이름</tr>
          <tr>메뉴</tr>
          <tr>수량</tr>
          <tr>예약날짜</tr>
          <tr>픽업시간</tr>
        </tr>
      </thead>
      <tbody>
        {% for post in posts%}
        <tr>
          <th>{{ order.id }}</th>
          <th>{{ order.store }}</th>
          <th>{{ orderlist.today_lineup }}</th>
          <th>{{ orderlist.order_quota }}</th>
          <th>{{ order.ordered_date }}</th>
          <th>{{ order.pickuptime }}</th>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>No Post.</p>
  {% endif %}
  <style>
    .button1 {display:inline-block; background-color:#f44336; color: #FFFFFF; padding: 14px 25px; text-align: center; text-decoration: none; font-size: 16px; margin-left: 20px; opacity: 0.9; border-radius: 5px;} 
    .button1:hover {color:white; background-color:pink; opacity:1.0;}
  </style>  
  <a href="{% url 'store:index' %}" class="button1" targer="_blank">메인페이지</a>

{% endblock %}

store/templates/store/review.html
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'store/style.css'%}" />
{% endblock %}

{% block content %}

<form action="{% url 'store:review_create' %}" method="post">
    {% csrf_token %}
    <h1>리뷰작성하기</h1>
    <h2>주문번호</h2>
    <input type="number" name="order_id">
    <h3>리뷰를 작성해주세요! </h3>
    <textarea cols="40" rows="10" name="review_content"></textarea>
   <br>
   <br>
   <br>
    <input type="submit" class=button1 value="등록하기">
    <style>
      .button1 {display:inline-block; background-color:#f44336; color: #FFFFFF; padding: 14px 25px; text-align: center; text-decoration: none; font-size: 16px; margin-left: 20px; opacity: 0.9; border-radius: 5px;} 
      .button1:hover {color:white; background-color:pink; opacity:1.0;}
    </style>  
</form>

{% endblock %}

store/templates/store/review_edit.html
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'store/style.css'%}" />
{% endblock %}

{% block content %}
<div class="container">
    <h1>리뷰수정하기</h1>
    {% if post.image %}
      <div>
        <img src="{{ post.image.url }}" alt="Post Image" />
      </div>
    {% endif %}   

    <form action="{% url 'review:update' post.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">
            <label for="body">본문</label>
            <textarea class="form-control" id="review+contemt" cols="40" rows="10" name="review_content">{{ post.body }}</textarea>
          </div>
    
          <div class="form-group">
            <label for="image">이미지</label>
            <input type="file" class="form-control-file" id="review_image" name="review_image" />
          </div>
    
          <button type="submit" class="btn btn-primary">수정하기</button>
        </form>
    
        <a href="{% url 'review:index' %}">목록</a>    
      </div>
{% endblock %}

store/templates/store/review_index.html
{% extends "base.html" %}

{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'store/style.css'%}" />
{% endblock %}

{% block content %}
  <div class="container">
    <h1 class="post_title">전체 리뷰</h1>

    {% if posts %}
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>#</th>
          <th>주문번호</th>
          <th>리뷰</th>
          <th>게시일</th>
          <th>수정</th>
        </tr>
      </thead>
      <tbody>
        {% for review in rivews %}
        <tr>
          <th>{{ review.id }}</th>
          <td>{{ order.order.id }}</td>
          <td>{{ review.review_content }}</td>
          <td>{{ post.created_at }}</td>
          <td><a href="{% url 'review:edit' review.id %}"></a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
      <p>No Posts.</p>
    {% endif %}

    <a href="{% url 'review' %}">리뷰작성하기</a> <!-- 이거를 마이페이지에다가만? -->
  </div>

  
{% endblock %}