accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('sign-up/', views.sign_up, name='sign_up'), 
    path('login/', views.login, name='login'),
]

store/urls.py
  
from django.contrib import admin
from django.urls import path
from . import views

app_name= 'store'

urlpatterns = [
    path('', views.index, name='home'),
    path('<str:biz_url>', views.index, name='index'),
    path('new/<str:biz_url>', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),
    path('<int:order_id>/delete/', views.delete, name='delete'),
    path('order_history/', views.order_history, name='order_history'),  
    path('review/<int:order_id>', views.review, name='review'),
    path('review_create/<int:order_id>', views.review_create, name='review_create'),
    #path('review/', views.review, name='review'),
    path('myprofile/', views.myprofile, name='myprofile'),
]

sweet_new/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('manager/', include('manager.urls')),
    path('accounts/', include('accounts.urls')),
    path('store/', include('store.urls', namespace="review")),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib import auth
from manager.models import Store



# Create your views here.
def sign_up(request):
    context = {}

    # POST Method
    if request.method == 'POST':
        if (request.POST['username'] and
                request.POST['password'] and
                request.POST['password'] == request.POST['password_check']):

            new_user = User.objects.create_user(
                username=request.POST['username'],
                password=request.POST['password'],
                first_name=request.POST['first_name'],
            )

            #사업자계정 추가정보 입력#
            new_storemember = Store(
                user = new_user,
                biz_name = request.POST['biz_name'],
                biz_num = request.POST['biz_num'],
                biz_url = request.POST['biz_url'],
                biz_insta = request.POST['biz_insta'],
                biz_address = request.POST['biz_address'],
                biz_tel = request.POST['biz_tel']
            )
            new_storemember.save()

            auth.login(request, new_user)
            return HttpResponse('정상적회원가입완료')

        else:
            context['error'] = '아이디와 비밀번호를 다시 확인해줴요.'

    # GET Method
    return render(request, 'accounts/sign_up.html', context)


def login(request):
    context = {}

    # POST Method
    if request.method == 'POST':
        if request.POST['username'] and request.POST['password']:

            user = auth.authenticate(
                request,
                username=request.POST['username'],
                password=request.POST['password']
            )

            if user is not None:
                auth.login(request, user)
                return HttpResponse("if user is not None이 트루라는 뜻")
            else:
                context['error'] = '아이디와 비밀번호를 다시 확인해주세요.'

        else:
            context['error'] = '아이디와 비밀번호를 모두 입력해주세요.'

    # GET Method
    return render(request, 'accounts/login.html', context)

accounts/templates/accounts/login.html
<div class="container">
    {% if error %}
      <div class="alert alert-danger" role="alert">
        {{ error }}
      </div>
    {% endif %}

    <form action="{% url 'accounts:login' %}" method="POST">
      {% csrf_token %}

      <h1>Login</h1>

      <div class="form-group">
        <label for="username">아이디</label>
        <input type="text" id="username" name="username" placeholder="아이디">
      </div>

      <div class="form-group">
        <label for="password">비밀번호</label>
        <input type="password" id="password" name="password" placeholder="비밀번호">
      </div>

      <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>

accounts/templates/accounts/sign_up.html
<div class="container">
    {% if error %}
    <div class="alert alert-danger" role="alert">
        {{ error }}
    </div>
    {% endif %}

    <form action="{% url 'accounts:sign_up' %}" method="POST">
        {% csrf_token %}

        <h1>Sign Up</h1>

        <div class="form-group">
            <label for="username">아이디</label>
            <input type="text" id="username" name="username" placeholder="아이디">
        </div>

        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" id="password" name="password" placeholder="비밀번호">
        </div>

        <div class="form-group">
            <label for="password_check">비밀번호 확인</label>
            <input type="password" id="password_check" name="password_check" placeholder="비밀번호 확인">
        </div>
        <div class="form-group">
            <label for="first_name">성함</label>
            <input type="text" id="first_name" name="first_name" placeholder="성함">
        </div>
        <hr>
        <p> 사업자회원가입이라면 아래 내용을 채워 주세요. </p>
        <!--사업자라면 아래 내용을 채워주세요-->
        <div class="form-group">
            <label for="biz_name">매장명</label>
            <input type="text" id="biz_name" name="biz_name" placeholder="매장명">
        </div>

        <div class="form-group">
            <label for="biz_num">사업자번호</label>
            <input type="number" id="biz_num" name="biz_num" placeholder="사업자번호">
        </div>

        <div class="form-group">
            <label for="biz_url">신청URL</label>
            <input type="text" id="biz_url" name="biz_url" placeholder="신청URL">
        </div>

        <div class="form-group">
            <label for="biz_insta">매장인스타ID</label>
            <input type="text" id="biz_insta" name="biz_insta" placeholder="매장인스타ID">
        </div>

        <div class="form-group">
            <label for="biz_address">매장주소</label>
            <input type="text" id="biz_address" name="biz_address" placeholder="매장주소">
        </div>

        <div class="form-group">
            <label for="biz_tel">매장연락처</label>
            <input type="number" id="biz_tel" name="biz_tel" placeholder="매장연락처">
        </div>
        
    <button type="submit" class="btn btn-primary">회원가입</button>

    </form>
</div>